### ISSUE TITLE
In-app messages don’t appear to work

### ISSUE THREAD

**Issue by heymartinadams** [userlistio/userlist-javascript#24]
In-app messages don’t seem to work with my web app (even though the backend says they were sent).

Using the `@userlist/widget` package doesn’t work (`undefined`), and setting the JS script manually with a server-generated token (per your docs) also doesn’t appear to work:

```js
// I use NextJS: https://nextjs.org/docs/basic-features/script
import Script from 'next/script'

const appScripts = ({ userlist }) => (
<Script id='userlist'>{`window.userlist=window.userlist||function(){(userlist.q=userlist.q||[]).push(arguments)};`}</Script>

// `userlist` is the token once it’s been fetched from the server using your Node.js example: https://userlist.com/docs/in-app-messages/setup/
<script async data-userlist={userlist} src='https://js.userlist.com/v1'></script>
)

export default appScripts
```

I can correctly identify that the script’s token has populated the `data-userlist` attribute upon load:
![CleanShot 2021-11-20 at 15 29 24@2x](https://user-images.githubusercontent.com/11673745/142743828-5117181a-1143-4995-9960-894dd91f4c9e.png)
...
<img width="630" alt="CleanShot 2021-11-20 at 15 30 39@2x" src="https://user-images.githubusercontent.com/11673745/142743845-03704bc1-13c6-4321-80d6-ddb5497986d5.png">

However, even if the “Userlist Automation” sends an in-app message a few minutes after correct load (as confirmed by dashboard), I as a user still don’t see an in-app message.

Note: I’m only using *server-side tracking* (`@userlist/push`), not client-side tracking, since [your docs](https://userlist.com/docs/in-app-messages/setup/#client-side-tracking) made it clear I just have to insert the `script` tags for in-app messages to work.

What might I be missing?

**Comment by benedikt** [comment]
@heymartinadams Do you get any error messages in the JavaScript console or do you see successful requests to https://api.widget.userlist.com in the Network tab? 

On successful initialization, you should also see a `userlist-container` in your DOM:

<img width="618" alt="CleanShot 2021-11-21 at 10 01 40@2x" src="https://user-images.githubusercontent.com/9696/142756049-39cb4e42-2698-4bec-adbc-e4552078992d.png">

**Comment by heymartinadams** [comment]
@benedikt no requests to any `userlist.com`, and no `userlist-container` either 😕

I call the script [here](https://github.com/ConsciousApps/LifePurposeApp/blob/main/design/layouts/app/Scripts.js#L15-L16) from the main [`_app.js`](https://github.com/ConsciousApps/LifePurposeApp/blob/main/pages/_app.js#L49) file.

Upon load, I [query](https://github.com/ConsciousApps/LifePurposeApp/blob/main/hooks/app/message/index.js) the backend to [get the token](https://github.com/ConsciousApps/LifePurposeApp/blob/main/pages/api/message/index.js), which I then set so that it gets passed back to the `data-userlist` attribute.

**Comment by benedikt** [comment]
@heymartinadams Instead of passing the token to the script tag, you can also leave it out of it and call `userlist('init', 'token-here');`. This might work better in your setup.

**Comment by heymartinadams** [comment]
@benedikt tried it, and called [`userlist('init', token)`](https://github.com/ConsciousApps/LifePurposeApp/blob/dev/hooks/app/message/index.js) but still no network request to `userlist` or DOM element. 🤔

**Comment by benedikt** [comment]
@heymartinadams That's weird. I just signed up for your app and while it doesn't work out-of-the-box the messages showed up once I manually called `userlist('init', token);` in the console 🤨



<img width="1072" alt="CleanShot 2021-11-22 at 08 17 00@2x" src="https://user-images.githubusercontent.com/9696/142819506-fb89ef7a-b185-4f5a-95ec-b75331ecf977.png">

**Comment by heymartinadams** [comment]
Got it to work, @benedikt! Calling `userlist('init', token);`  did the trick (and not sure what’s different now from before).

Two things of note:
1. It now works in production, but for some reason not on `localhost`. In `localhost`, the `<div class="userlist-container userlist-bottom-right">...</div>` doesn’t get created.

2. In production, the `<div>` gets created, but it only shows on Safari, not in Chrome for macOS. Once I add `height: auto;` to the DOM element `.userlist-container.userlist-bottom-right`, then it shows.

## issue
![CleanShot 2021-11-22 at 10 37 26@2x](https://user-images.githubusercontent.com/11673745/142916792-6cbfab5f-d879-4a25-9f14-0efacef0fda7.png)
## fix
![CleanShot 2021-11-22 at 10 38 16@2x](https://user-images.githubusercontent.com/11673745/142916901-a2200de0-6357-4f3c-8d0f-cc4b1efd3621.png)

3.

**Comment by benedikt** [comment]
@heymartinadams Glad it's working!

I'll look into the localhost issue. 

The container is hidden until a message arrives. The widget then explicitly sets a height to match the message content's height.

**Comment by heymartinadams** [comment]
Thanks!

CSS `height`: I don't believe it's happening in Chrome (the CSS screenshot above was for an existing message that had already arrived).

**Comment by heymartinadams** [comment]
Since I got this issue to work, closing it.
