### ISSUE TITLE
`userlist.events.create` cannot track Company

### ISSUE THREAD

**Issue by heymartinadams** [userlistio/userlist-javascript#26]
`userlist.events.create` seems to require a `user` property, even if I supply it with a `company` property. [According to your docs](https://userlist.com/docs/getting-started/integration-guide/), I should be able to provide either a `user` or a `company`.

When I supply this:
```js
userlist.events.create({
  name: 'registration_success',
  company: 'some company',
  properties: {...}
})
```
I get this:
<img width="394" alt="CleanShot 2022-02-01 at 16 26 25@2x" src="https://user-images.githubusercontent.com/11673745/152073702-d925871b-4d64-4bae-a539-b8664a498d5f.png">

![CleanShot 2022-02-01 at 16 25 41@2x](https://user-images.githubusercontent.com/11673745/152073653-4ee8a9a7-4005-4e25-b394-474b749f473e.png)

**Comment by heymartinadams** [comment]
Looks like I was able to create a workaround:
```js
userlist.events.create({
  name: 'registration_success',
  user: 'n/a',
  company: 'some company',
  properties: {...}
})
```

**Comment by benedikt** [comment]
Hey @heymartinadams! 

Thanks for letting us know about this. We just updated the @userlist/push package to support events without a dedicated user. Please update to v0.2.0. 

Bests,

Benedikt

**Comment by heymartinadams** [comment]
Thanks @benedikt! 🚀
